// Friends Profile Data

export const FriendsProfileData = [
  {
    name: 'Surbhi_Rana',
    accountName: 'surbhi',
    profileImage: require('../../Storage/Images/posts1.jpeg'),
    posts: 78,
    followers: 8768,
    following: 112,
    follow: false,
  },
  {
    name: 'Falak Hasija',
    accountName: 'falak_hasija1509',
    profileImage: require('../../Storage/Images/posts2.jpeg'),
    posts: 24,
    followers: 1253,
    following: 64,
    follow: false,
  },
  {
    name: 'Falak Hasija',
    accountName: 'falak_hasija1509',
    profileImage: require('../../Storage/Images/posts3.jpeg'),
    posts: 21,
    followers: 7886,
    following: 32,
    follow: false,
  },
  {
    name: 'Beautiful Gifts',
    accountName: 'Gifts_here',
    profileImage: require('../../Storage/Images/posts4.jpeg'),
    posts: 123,
    followers: 64253,
    following: 32,
    follow: false,
  },
  {
    name: 'Roushi K',
    accountName: 'The Roccc',
    profileImage: require('../../Storage/Images/posts5.jpeg'),
    posts: 784,
    followers: 8973,
    following: 217,
    follow: false,
  },
  {
    name: 'mr_bean',
    accountName: 'Mr Bean',
    profileImage: require('../../Storage/Images/posts6.jpeg'),
    posts: 879,
    followers: '564k',
    following: 32,
    follow: false,
  },
  {
    name: 'Akaash Singh',
    accountName: 'Mr beast',
    profileImage: require('../../Storage/Images/posts7.jpeg'),
    posts: 321,
    followers: '435k',
    following: 11,
    follow: false,
  },
  {
    name: 'Satyam Badola',
    accountName: 'suraj_b',
    profileImage: require('../../Storage/Images/search3.jpeg'),
    posts: 321,
    followers: '763k',
    following: 311,
    follow: false,
  },
  {
    name: 'Shrey',
    accountName: 'ShreyAggarwal',
    profileImage: require('../../Storage/Images/search2.jpeg'),
    posts: 123,
    followers: 21344,
    following: 1,
    follow: false,
  },
  {
    name: 'angry_bird',
    accountName: 'Angry Bird',
    profileImage: require('../../Storage/Images/search1.jpeg'),
    posts: 243,
    followers: 27391,
    following: 211,
    follow: false,
  },
  {
    name: 'Steve',
    accountName: 'Captain America',
    profileImage: require('../../Storage/Images/search4.jpeg'),
    posts: 786,
    followers: '987k',
    following: 24,
    follow: false,
  },
  {
    name: 'All about DU',
    accountName: 'DU Official',
    profileImage: require('../../Storage/Images/search7.jpeg'),
    posts: '1.2k',
    followers: '1.2M',
    following: 120,
    follow: false,
  },
  {
    name: '_don_',
    accountName: 'Don',
    profileImage: require('../../Storage/Images/search9.jpeg'),
    posts: 542,
    followers: 2761,
    following: 162,
    follow: false,
  },
];
