export const posts = [
  {
    name: 'Alex_Day',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    place: 'Singapore',
    image: require('../Storage/Images/Feed_Page/feed1.jpeg'),
    postStatus: 'Enjoyed this amazing meal at the New Era cafe 🍔🍿',
    likes: 289,
  },
  {
    name: 'Cristina_Brown',
    avatar: 'https://randomuser.me/api/portraits/women/79.jpg',
    place: 'New York',
    postStatus: "It's Cold in here ❄️🥶",
    image: require('../Storage/Images/Feed_Page/feed2.jpeg'),
    likes: 195,
  },
  {
    name: 'Richard',
    avatar: 'https://randomuser.me/api/portraits/men/61.jpg',
    place: 'USA',
    postStatus: 'The view looks just as amazing as it feels ⛰',
    image: require('../Storage/Images/Feed_Page/feed3.webp'),
    likes: 272,
  },
  {
    name: 'Emily_Watson',
    avatar:
      'https://images.pexels.com/photos/61100/pexels-photo-61100.jpeg?crop=faces&fit=crop&h=200&w=200&auto=compress&cs=tinysrgb',
    place: 'UK',
    postStatus: "Isn't it beautiful ☘️ ",
    image: require('../Storage/Images/Feed_Page/feed4.jpeg'),
    likes: 471,
  },
  {
    name: 'Cole.Sam',
    avatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&fit=crop&h=200&w=200&s=a72ca28288878f8404a795f39642a46f',
    place: 'Singapore',
    postStatus: 'Some Dessert 🍧',
    image: require('../Storage/Images/Feed_Page/feed5.webp'),
    likes: 171,
  },
  {
    name: 'Rachel.Green',
    avatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&fit=crop&h=200&w=200&s=707b9c33066bf8808c934c8ab394dff6',
    place: 'New York',
    postStatus: 'Serenity ☘️ ',
    image: require('../Storage/Images/Feed_Page/feed6.jpeg'),
    likes: 451,
  },
  {
    name: 'Sid_D',
    avatar: 'https://randomuser.me/api/portraits/men/86.jpg',
    place: 'Singapore',
    postStatus: 'All pink 🌷 ',
    image: require('../Storage/Images/Feed_Page/feed7.jpeg'),
    likes: 762,
  },
  {
    name: 'Shain',
    avatar: 'https://randomuser.me/api/portraits/women/32.jpg',
    place: 'Thailand',
    postStatus: 'Black and White 🖤',
    image: require('../Storage/Images/Feed_Page/feed8.jpeg'),
    likes: 348,
  },
  {
    name: 'Amaira',
    avatar: 'https://randomuser.me/api/portraits/women/18.jpg',
    place: 'US',
    postStatus: 'Be confident ALWAYS ✌️',
    image: require('../Storage/Images/Feed_Page/feed9.webp'),
    likes: 871,
  },
  {
    name: 'Rez_Shein',
    avatar: 'https://randomuser.me/api/portraits/women/86.jpg',
    place: 'UK',
    postStatus: 'Say Cheese 🧀',
    image: require('../Storage/Images/Feed_Page/feed10.jpeg'),
    likes: 943,
  },
  {
    name: 'Reza',
    avatar: 'https://randomuser.me/api/portraits/men/6.jpg',
    place: 'Mexico',
    postStatus: "It's all about the moment 🖌",
    image: require('../Storage/Images/Feed_Page/feed11.jpeg'),
    likes: 569,
  },
  {
    name: 'Kanye ',
    avatar: 'https://randomuser.me/api/portraits/women/6.jpg',
    place: 'Singapore',
    postStatus: '🌿 ',
    image: require('../Storage/Images/Feed_Page/feed13.webp'),
    likes: 760,
  },
  {
    name: 'Piyush Sharma',
    avatar: 'https://randomuser.me/api/portraits/men/71.jpg',
    place: 'India',
    postStatus: 'Hustle 💪',
    image: require('../Storage/Images/Feed_Page/feed12.jpeg'),
    likes: 265,
  },
  {
    name: 'Sid S.',
    avatar: 'https://randomuser.me/api/portraits/women/80.jpg',
    place: 'France',
    postStatus: 'Easter is coming.. 🐣',
    image: require('../Storage/Images/Feed_Page/feed16.webp'),
    likes: 879,
  },
  {
    name: 'Mrunali',
    avatar: 'https://randomuser.me/api/portraits/women/17.jpg',
    place: 'Cuba',
    postStatus: '🌻',
    image: require('../Storage/Images/Feed_Page/feed14.webp'),
    likes: 670,
  },
  {
    name: 'Harry',
    avatar: 'https://randomuser.me/api/portraits/men/11.jpg',
    place: 'UK',
    postStatus: 'You in? 🧚‍♀️',
    image: require('../Storage/Images/Feed_Page/feed17.jpeg'),
    likes: 348,
  },
  {
    name: 'Chandler',
    avatar: 'https://randomuser.me/api/portraits/men/46.jpg',
    place: 'New York',
    postStatus: 'Do you remember the tastiest cheesecake? 🧁',
    image: require('../Storage/Images/Feed_Page/feed15.jpeg'),
    likes: 471,
  },
  {
    name: 'Shikha Sood',
    avatar: 'https://randomuser.me/api/portraits/women/76.jpg',
    place: 'India',
    postStatus: "It's therapy indeed 🖌 ",
    image: require('../Storage/Images/Feed_Page/feed18.jpeg'),
    likes: 256,
  },
  {
    name: 'Jill',
    avatar: 'https://randomuser.me/api/portraits/women/69.jpg',
    place: 'Russia',
    postStatus: '✨💫',
    image: require('../Storage/Images/Feed_Page/feed20.webp'),
    likes: 167,
  },

  {
    name: 'Emily',
    avatar: 'https://randomuser.me/api/portraits/men/88.jpg',
    place: 'Britain',
    postStatus: '👩‍💻 ',
    image: require('../Storage/Images/Feed_Page/feed22.jpeg'),
    likes: 651,
  },
  {
    name: 'Brandon',
    avatar: 'https://randomuser.me/api/portraits/women/36.jpg',
    place: 'Singapore',
    postStatus: 'The shore 🌊🐚',
    image: require('../Storage/Images/Feed_Page/feed21.webp'),
    likes: 567,
  },
  {
    name: 'Courtney',
    avatar: 'https://randomuser.me/api/portraits/women/16.jpg',
    place: 'Singapore',
    postStatus: '🌿 ',
    image: require('../Storage/Images/Feed_Page/feed24.jpeg'),
    likes: 469,
  },
  {
    name: 'Stefan Salvatore',
    avatar: 'https://randomuser.me/api/portraits/men/72.jpg',
    place: 'Mystic Falls',
    postStatus: '🌳🍃 ',
    image: require('../Storage/Images/Feed_Page/feed23.jpeg'),
    likes: 471,
  },
  {
    name: 'Joey',
    avatar: 'https://randomuser.me/api/portraits/men/35.jpg',
    place: 'US',
    postStatus: "It's all Food 🍕",
    image: require('../Storage/Images/Feed_Page/feed25.webp'),
    likes: 781,
  },
  {
    name: 'Sreshtha',
    avatar: 'https://randomuser.me/api/portraits/women/39.jpg',
    place: 'US',
    postStatus: 'London 🖤',
    image: require('../Storage/Images/Feed_Page/feed26.jpeg'),
    likes: 563,
  },
];
